#!/usr/bin/env node
/**
 * Regenerates `src/version.ts` from `package.json` so the wrapper's
 * `version` field stays in sync without reading `package.json` at
 * runtime (which is awkward in ESM and breaks under bundlers).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");
const pkg = JSON.parse(readFileSync(resolve(repoRoot, "package.json"), "utf8"));
const version = pkg.version;

if (typeof version !== "string" || version.length === 0) {
  console.error("gen-version: package.json has no string `version` field");
  process.exit(1);
}

const banner =
  "// AUTO-GENERATED by scripts/gen-version.mjs. Do not edit; re-run `npm run gen:version`.\n";
const body = `export const PKG_VERSION: string = ${JSON.stringify(version)};\n`;
writeFileSync(resolve(repoRoot, "src", "version.ts"), banner + body);
console.log(`gen-version: wrote src/version.ts (PKG_VERSION = ${JSON.stringify(version)})`);
